#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.16
# from Racc grammar file "".
#

require 'racc/parser.rb'

require "strscan"

module ErlangConfigParser
  class Parser < Racc::Parser

module_eval(<<'...end parser.ry/module_eval...', 'parser.ry', 28)

def parse(str)
  ss = StringScanner.new(str)
  @tokens = []

  until ss.eos?
    ss.scan(/<<"((?:[^"\\]|\\.)*)">>/)    ? @tokens << [:BIT_STRING,  ss[1]] :
    ss.scan(/"((?:[^"\\]|\\.)*)"/)        ? @tokens << [:STRING,      ss[1]] :
    ss.scan(/[+-]?\d+\.\d+(?:e[+-]\d+)?/) ? @tokens << [:FLOAT,       ss.matched] :
    ss.scan(/[+-]?\d+/)                   ? @tokens << [:INTEGER,     ss.matched] :
    ss.scan(/\[/)                         ? @tokens << [:LIST_BEGIN,  ss.matched] :
    ss.scan(/\]/)                         ? @tokens << [:LIST_END,    ss.matched] :
    ss.scan(/{/)                          ? @tokens << [:TUPLE_BEGIN, ss.matched] :
    ss.scan(/}/)                          ? @tokens << [:TUPLE_END,   ss.matched] :
    ss.scan(/'((?:[^'\\]|\\.)*)'/)        ? @tokens << [:ATOM,        ss[1]] :
    ss.scan(/[a-z][\w@]*/)                ? @tokens << [:ATOM,        ss.matched] :
    ss.scan(/,/)                          ? @tokens << [:COMMA,       ss.matched] :
    ss.scan(/\s/)                         ? nil :
    ss.scan(/\./)                         ? break :
    (raise "scanner error at '%s'" % ss.peek(20))
  end

  do_parse
end

def next_token
  @tokens.shift
end
...end parser.ry/module_eval...
##### State transition tables begin ###

racc_action_table = [
     4,    20,     5,    19,    21,    12,    13,    14,    15,    16,
     4,     8,     5,    22,    21,    12,    13,    14,    15,    16,
     4,     6,     5,    18,   nil,    12,    13,    14,    15,    16,
     4,   nil,     5 ]

racc_action_check = [
    21,     7,    21,     6,     7,    21,    21,    21,    21,    21,
     4,     4,     4,    17,    17,     4,     4,     4,     4,     4,
     5,     1,     5,     5,   nil,     5,     5,     5,     5,     5,
     0,   nil,     0 ]

racc_action_pointer = [
    28,    21,   nil,   nil,     8,    18,     3,    -2,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     8,   nil,   nil,
   nil,    -2,   nil,   nil ]

racc_action_default = [
   -16,   -16,    -1,    -2,   -16,   -16,   -16,   -16,    -4,    -7,
    -9,   -10,   -11,   -12,   -13,   -14,   -15,   -16,    -6,    24,
    -3,   -16,    -5,    -8 ]

racc_goto_table = [
     7,    17,     1,     2,     3,    23 ]

racc_goto_check = [
     4,     4,     1,     2,     3,     5 ]

racc_goto_pointer = [
   nil,     2,     3,     4,    -4,   -16 ]

racc_goto_default = [
   nil,   nil,    10,    11,   nil,     9 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  3, 14, :_reduce_3,
  2, 14, :_reduce_4,
  3, 15, :_reduce_5,
  2, 15, :_reduce_6,
  1, 16, :_reduce_7,
  3, 16, :_reduce_8,
  1, 17, :_reduce_none,
  1, 17, :_reduce_none,
  1, 17, :_reduce_11,
  1, 17, :_reduce_12,
  1, 17, :_reduce_13,
  1, 17, :_reduce_14,
  1, 17, :_reduce_15 ]

racc_reduce_n = 16

racc_shift_n = 24

racc_token_table = {
  false => 0,
  :error => 1,
  :LIST_BEGIN => 2,
  :LIST_END => 3,
  :TUPLE_BEGIN => 4,
  :TUPLE_END => 5,
  :COMMA => 6,
  :ATOM => 7,
  :BIT_STRING => 8,
  :STRING => 9,
  :INTEGER => 10,
  :FLOAT => 11 }

racc_nt_base = 12

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LIST_BEGIN",
  "LIST_END",
  "TUPLE_BEGIN",
  "TUPLE_END",
  "COMMA",
  "ATOM",
  "BIT_STRING",
  "STRING",
  "INTEGER",
  "FLOAT",
  "$start",
  "statement",
  "list",
  "tuple",
  "elements",
  "element" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

module_eval(<<'.,.,', 'parser.ry', 5)
  def _reduce_3(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 6)
  def _reduce_4(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 8)
  def _reduce_5(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 9)
  def _reduce_6(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 11)
  def _reduce_7(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 12)
  def _reduce_8(val, _values, result)
     result << val[2]
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.ry', 16)
  def _reduce_11(val, _values, result)
     result = val[0].to_sym
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 17)
  def _reduce_12(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 18)
  def _reduce_13(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 19)
  def _reduce_14(val, _values, result)
     result = val[0].to_i
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 20)
  def _reduce_15(val, _values, result)
     result = val[0].to_f
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module ErlangConfigParser
