#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.2
# from Racc grammar file "".
#

require 'racc/parser.rb'

require "strscan"

module ErlangConfigParser
  class Parser < Racc::Parser

module_eval(<<'...end parser.ry/module_eval...', 'parser.ry', 31)

def parse(str)
  ss = StringScanner.new(str)
  @tokens = []

  until ss.eos?
    ss.scan(/"((?:[^"\\]|\\.)*)"/)        ? @tokens << [:STRING,      ss[1]] :
    ss.scan(/[+-]?\d+\.\d+(?:e[+-]\d+)?/) ? @tokens << [:FLOAT,       ss.matched] :
    ss.scan(/[+-]?\d+/)                   ? @tokens << [:INTEGER,     ss.matched] :
    ss.scan(/\[/)                         ? @tokens << [:LIST_BEGIN,  ss.matched] :
    ss.scan(/\]/)                         ? @tokens << [:LIST_END,    ss.matched] :
    ss.scan(/{/)                          ? @tokens << [:TUPLE_BEGIN, ss.matched] :
    ss.scan(/}/)                          ? @tokens << [:TUPLE_END,   ss.matched] :
    ss.scan(/<</)                         ? @tokens << [:BIN_BEGIN,   ss.matched] :
    ss.scan(/>>/)                         ? @tokens << [:BIN_END,     ss.matched] :
    ss.scan(/'((?:[^'\\]|\\.)*)'/)        ? @tokens << [:ATOM,        ss[1]] :
    ss.scan(/[a-z][\w_@]*/)               ? @tokens << [:ATOM,        ss.matched] :
    ss.scan(/,/)                          ? @tokens << [:COMMA,       ss.matched] :
    ss.scan(/\s/)                         ? nil :
    ss.scan(/\./)                         ? break :
    (raise "scanner error")
  end

  do_parse
end

def next_token
  @tokens.shift
end
...end parser.ry/module_eval...
##### State transition tables begin ###

racc_action_table = [
     4,     8,     5,    25,     9,    15,    21,    22,    14,    16,
    17,     4,    22,     5,    19,     9,    15,    23,    24,    14,
    16,    17,     4,     4,     5,     5,     9,    15,     6,    20,
    14,    16,    17,    27 ]

racc_action_check = [
     4,     4,     4,    18,     4,     4,     7,    18,     4,     4,
     4,     5,     7,     5,     5,     5,     5,     9,     9,     5,
     5,     5,    22,     0,    22,     0,    22,    22,     1,     6,
    22,    22,    22,    23 ]

racc_action_pointer = [
    21,    28,   nil,   nil,    -2,     9,    29,     3,   nil,    10,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    -2,   nil,
   nil,   nil,    20,    25,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -18,   -18,    -1,    -2,   -18,   -18,   -18,   -18,    -4,   -18,
    -9,   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,    -6,
    28,    -3,   -18,   -18,    -8,    -5,   -10,    -7 ]

racc_goto_table = [
     7,    18,     1,     2,     3,    26 ]

racc_goto_check = [
     4,     4,     1,     2,     3,     6 ]

racc_goto_pointer = [
   nil,     2,     3,     4,    -4,   nil,   -17 ]

racc_goto_default = [
   nil,   nil,    11,    12,   nil,    13,    10 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  3, 15, :_reduce_3,
  2, 15, :_reduce_4,
  3, 16, :_reduce_5,
  2, 16, :_reduce_6,
  3, 18, :_reduce_7,
  2, 18, :_reduce_8,
  1, 17, :_reduce_9,
  3, 17, :_reduce_10,
  1, 19, :_reduce_none,
  1, 19, :_reduce_none,
  1, 19, :_reduce_none,
  1, 19, :_reduce_14,
  1, 19, :_reduce_15,
  1, 19, :_reduce_16,
  1, 19, :_reduce_17 ]

racc_reduce_n = 18

racc_shift_n = 28

racc_token_table = {
  false => 0,
  :error => 1,
  :LIST_BEGIN => 2,
  :LIST_END => 3,
  :TUPLE_BEGIN => 4,
  :TUPLE_END => 5,
  :BIN_BEGIN => 6,
  :STRING => 7,
  :BIN_END => 8,
  :COMMA => 9,
  :ATOM => 10,
  :INTEGER => 11,
  :FLOAT => 12 }

racc_nt_base = 13

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LIST_BEGIN",
  "LIST_END",
  "TUPLE_BEGIN",
  "TUPLE_END",
  "BIN_BEGIN",
  "STRING",
  "BIN_END",
  "COMMA",
  "ATOM",
  "INTEGER",
  "FLOAT",
  "$start",
  "statement",
  "list",
  "tuple",
  "elements",
  "bin_string",
  "element" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

module_eval(<<'.,.,', 'parser.ry', 5)
  def _reduce_3(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 6)
  def _reduce_4(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 8)
  def _reduce_5(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 9)
  def _reduce_6(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 11)
  def _reduce_7(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 12)
  def _reduce_8(val, _values, result)
     result = ""
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 14)
  def _reduce_9(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 15)
  def _reduce_10(val, _values, result)
     result << val[2]
    result
  end
.,.,

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

module_eval(<<'.,.,', 'parser.ry', 20)
  def _reduce_14(val, _values, result)
     result = val[0].to_sym
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 21)
  def _reduce_15(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 22)
  def _reduce_16(val, _values, result)
     result = val[0].to_i
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 23)
  def _reduce_17(val, _values, result)
     result = val[0].to_f
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module ErlangConfigParser
